### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by tripleo1** [fake-name/ReadableWebProxy#728]
Can you provide a Docker image for this as it seems hard to set up. I want all the features, includeing AutoTriever and I dont know what amqp is or saltstack.

**Comment by fake-name** [comment]
My entire infrastructure is based around proxmox/lxc, so basically I don't do anything with docker ever, or have any interest in doing so. Nesting multiple virtualization systems just to manage docker is silly (I also really don't /like/ docker, IMHO). 

Sorry!

> I want all the features, includeing AutoTriever and I dont know what amqp is or saltstack.

You could run the synchronous web views locally only, but the entire spider cannot function without a DNS-resolvable AMQP server (tested only with rabbitmq). Additionally, unless you manually set up workers, you need a saltstack master instance that's configured to deploy to at least one of Vultr/DigitalOcean/Linode. 


If you don't know what AMQP or SaltStack is, I think setting up a full instance of this is probably going to be rather challenging for you.

**Comment by tripleo1** [comment]
Can you walk me thru your setup?

**Comment by fake-name** [comment]
Not trivially. What have you done so far?  You should be able to get to bullet ~9 of the [readme.md](https://github.com/fake-name/ReadableWebProxy/blob/master/README.md) without help.

Why are you trying to set this up in the first place? It's not of much use to anyone but me, I've mostly posted it because I figure a few people might find digging around in the source of value.

**Comment by tripleo1** [comment]
I want to archive my web history.
